url: "https://funeoz.github.io"
title: "Funeoz's blog"
baseurl: "" 
description: "My blog about software development, cybersecurity and more..."

sass:
  sass_dir: _sass

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 5
paginate_path: "/page:num/"